### ISSUE TITLE
Dashboard-Digital-Meet

### ISSUE THREAD

**Issue by Tine0814** [JMSevilla/mdr-fe-ts-v2#69]
After logging in, when you click on the 'Digital Meet' feature, you will be redirected to the login page once again. Upon logging in again, if you try to access the 'Digital Meet' feature once more, you will encounter an error.

"Unhandled Runtime Error
TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined"

 export const decrypt = (data: any) => {
> 15 | const binaryData = new Buffer(data, ENCODING);
     |                   ^
  16 | const iv = binaryData.slice(-IV_LENGTH);
  17 | const encryptedData = binaryData.slice(0, binaryData.length - IV_LENGTH);
  18 | const decipher = crypto.createDecipheriv(ALGORITHM, key_in_bytes, iv);

**Comment by JMSevilla** [comment]
Resolved this one.
